//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dmbot_serial package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dmbot_serial__MY_CFGCONFIG_H__
#define __dmbot_serial__MY_CFGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dmbot_serial
{
  class my_cfgConfigStatics;

  class my_cfgConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(my_cfgConfig &config, const my_cfgConfig &max, const my_cfgConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const my_cfgConfig &config1, const my_cfgConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, my_cfgConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const my_cfgConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, my_cfgConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const my_cfgConfig &config) const = 0;
      virtual void getValue(const my_cfgConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T my_cfgConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T my_cfgConfig::* field;

      virtual void clamp(my_cfgConfig &config, const my_cfgConfig &max, const my_cfgConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const my_cfgConfig &config1, const my_cfgConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, my_cfgConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const my_cfgConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, my_cfgConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const my_cfgConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const my_cfgConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, my_cfgConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, my_cfgConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<my_cfgConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(my_cfgConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("pos_set0"==(*_i)->name){pos_set0 = boost::any_cast<double>(val);}
        if("pos_set1"==(*_i)->name){pos_set1 = boost::any_cast<double>(val);}
        if("pos_set2"==(*_i)->name){pos_set2 = boost::any_cast<double>(val);}
        if("pos_set3"==(*_i)->name){pos_set3 = boost::any_cast<double>(val);}
        if("pos_set4"==(*_i)->name){pos_set4 = boost::any_cast<double>(val);}
        if("pos_set5"==(*_i)->name){pos_set5 = boost::any_cast<double>(val);}
        if("pos_set6"==(*_i)->name){pos_set6 = boost::any_cast<double>(val);}
        if("pos_set7"==(*_i)->name){pos_set7 = boost::any_cast<double>(val);}
        if("pos_set8"==(*_i)->name){pos_set8 = boost::any_cast<double>(val);}
        if("pos_set9"==(*_i)->name){pos_set9 = boost::any_cast<double>(val);}
        if("vel_set0"==(*_i)->name){vel_set0 = boost::any_cast<double>(val);}
        if("vel_set1"==(*_i)->name){vel_set1 = boost::any_cast<double>(val);}
        if("vel_set2"==(*_i)->name){vel_set2 = boost::any_cast<double>(val);}
        if("vel_set3"==(*_i)->name){vel_set3 = boost::any_cast<double>(val);}
        if("vel_set4"==(*_i)->name){vel_set4 = boost::any_cast<double>(val);}
        if("vel_set5"==(*_i)->name){vel_set5 = boost::any_cast<double>(val);}
        if("vel_set6"==(*_i)->name){vel_set6 = boost::any_cast<double>(val);}
        if("vel_set7"==(*_i)->name){vel_set7 = boost::any_cast<double>(val);}
        if("vel_set8"==(*_i)->name){vel_set8 = boost::any_cast<double>(val);}
        if("vel_set9"==(*_i)->name){vel_set9 = boost::any_cast<double>(val);}
        if("torque_set0"==(*_i)->name){torque_set0 = boost::any_cast<double>(val);}
        if("torque_set1"==(*_i)->name){torque_set1 = boost::any_cast<double>(val);}
        if("torque_set2"==(*_i)->name){torque_set2 = boost::any_cast<double>(val);}
        if("torque_set3"==(*_i)->name){torque_set3 = boost::any_cast<double>(val);}
        if("torque_set4"==(*_i)->name){torque_set4 = boost::any_cast<double>(val);}
        if("torque_set5"==(*_i)->name){torque_set5 = boost::any_cast<double>(val);}
        if("torque_set6"==(*_i)->name){torque_set6 = boost::any_cast<double>(val);}
        if("torque_set7"==(*_i)->name){torque_set7 = boost::any_cast<double>(val);}
        if("torque_set8"==(*_i)->name){torque_set8 = boost::any_cast<double>(val);}
        if("torque_set9"==(*_i)->name){torque_set9 = boost::any_cast<double>(val);}
        if("kp_set"==(*_i)->name){kp_set = boost::any_cast<double>(val);}
        if("kd_set"==(*_i)->name){kd_set = boost::any_cast<double>(val);}
      }
    }

    double pos_set0;
double pos_set1;
double pos_set2;
double pos_set3;
double pos_set4;
double pos_set5;
double pos_set6;
double pos_set7;
double pos_set8;
double pos_set9;
double vel_set0;
double vel_set1;
double vel_set2;
double vel_set3;
double vel_set4;
double vel_set5;
double vel_set6;
double vel_set7;
double vel_set8;
double vel_set9;
double torque_set0;
double torque_set1;
double torque_set2;
double torque_set3;
double torque_set4;
double torque_set5;
double torque_set6;
double torque_set7;
double torque_set8;
double torque_set9;
double kp_set;
double kd_set;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set4;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set6;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set7;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set8;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_set9;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set4;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set6;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set7;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set8;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_set9;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set4;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set6;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set7;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set8;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double torque_set9;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kp_set;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double kd_set;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("my_cfgConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const my_cfgConfig &__max__ = __getMax__();
      const my_cfgConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const my_cfgConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const my_cfgConfig &__getDefault__();
    static const my_cfgConfig &__getMax__();
    static const my_cfgConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const my_cfgConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void my_cfgConfig::ParamDescription<std::string>::clamp(my_cfgConfig &config, const my_cfgConfig &max, const my_cfgConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class my_cfgConfigStatics
  {
    friend class my_cfgConfig;

    my_cfgConfigStatics()
    {
my_cfgConfig::GroupDescription<my_cfgConfig::DEFAULT, my_cfgConfig> Default("Default", "", 0, 0, true, &my_cfgConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set0 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set0 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set0 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set0", "double", 0, "pos_set0", "", &my_cfgConfig::pos_set0)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set0", "double", 0, "pos_set0", "", &my_cfgConfig::pos_set0)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set1 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set1 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set1 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set1", "double", 0, "pos_set1", "", &my_cfgConfig::pos_set1)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set1", "double", 0, "pos_set1", "", &my_cfgConfig::pos_set1)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set2 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set2 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set2 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set2", "double", 0, "pos_set2", "", &my_cfgConfig::pos_set2)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set2", "double", 0, "pos_set2", "", &my_cfgConfig::pos_set2)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set3 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set3 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set3 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set3", "double", 0, "pos_set3", "", &my_cfgConfig::pos_set3)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set3", "double", 0, "pos_set3", "", &my_cfgConfig::pos_set3)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set4 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set4 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set4 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set4", "double", 0, "pos_set4", "", &my_cfgConfig::pos_set4)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set4", "double", 0, "pos_set4", "", &my_cfgConfig::pos_set4)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set5 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set5 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set5 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set5", "double", 0, "pos_set5", "", &my_cfgConfig::pos_set5)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set5", "double", 0, "pos_set5", "", &my_cfgConfig::pos_set5)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set6 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set6 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set6 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set6", "double", 0, "pos_set6", "", &my_cfgConfig::pos_set6)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set6", "double", 0, "pos_set6", "", &my_cfgConfig::pos_set6)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set7 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set7 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set7 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set7", "double", 0, "pos_set7", "", &my_cfgConfig::pos_set7)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set7", "double", 0, "pos_set7", "", &my_cfgConfig::pos_set7)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set8 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set8 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set8 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set8", "double", 0, "pos_set8", "", &my_cfgConfig::pos_set8)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set8", "double", 0, "pos_set8", "", &my_cfgConfig::pos_set8)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_set9 = -12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_set9 = 12.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_set9 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set9", "double", 0, "pos_set9", "", &my_cfgConfig::pos_set9)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("pos_set9", "double", 0, "pos_set9", "", &my_cfgConfig::pos_set9)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set0 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set0 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set0 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set0", "double", 0, "vel_set0", "", &my_cfgConfig::vel_set0)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set0", "double", 0, "vel_set0", "", &my_cfgConfig::vel_set0)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set1 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set1 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set1 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set1", "double", 0, "vel_set1", "", &my_cfgConfig::vel_set1)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set1", "double", 0, "vel_set1", "", &my_cfgConfig::vel_set1)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set2 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set2 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set2 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set2", "double", 0, "vel_set2", "", &my_cfgConfig::vel_set2)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set2", "double", 0, "vel_set2", "", &my_cfgConfig::vel_set2)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set3 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set3 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set3 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set3", "double", 0, "vel_set3", "", &my_cfgConfig::vel_set3)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set3", "double", 0, "vel_set3", "", &my_cfgConfig::vel_set3)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set4 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set4 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set4 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set4", "double", 0, "vel_set4", "", &my_cfgConfig::vel_set4)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set4", "double", 0, "vel_set4", "", &my_cfgConfig::vel_set4)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set5 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set5 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set5 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set5", "double", 0, "vel_set5", "", &my_cfgConfig::vel_set5)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set5", "double", 0, "vel_set5", "", &my_cfgConfig::vel_set5)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set6 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set6 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set6 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set6", "double", 0, "vel_set6", "", &my_cfgConfig::vel_set6)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set6", "double", 0, "vel_set6", "", &my_cfgConfig::vel_set6)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set7 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set7 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set7 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set7", "double", 0, "vel_set7", "", &my_cfgConfig::vel_set7)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set7", "double", 0, "vel_set7", "", &my_cfgConfig::vel_set7)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set8 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set8 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set8 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set8", "double", 0, "vel_set8", "", &my_cfgConfig::vel_set8)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set8", "double", 0, "vel_set8", "", &my_cfgConfig::vel_set8)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_set9 = -30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_set9 = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_set9 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set9", "double", 0, "vel_set9", "", &my_cfgConfig::vel_set9)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("vel_set9", "double", 0, "vel_set9", "", &my_cfgConfig::vel_set9)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set0 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set0 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set0 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set0", "double", 0, "torque_set0", "", &my_cfgConfig::torque_set0)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set0", "double", 0, "torque_set0", "", &my_cfgConfig::torque_set0)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set1 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set1 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set1 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set1", "double", 0, "torque_set1", "", &my_cfgConfig::torque_set1)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set1", "double", 0, "torque_set1", "", &my_cfgConfig::torque_set1)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set2 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set2 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set2 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set2", "double", 0, "torque_set2", "", &my_cfgConfig::torque_set2)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set2", "double", 0, "torque_set2", "", &my_cfgConfig::torque_set2)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set3 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set3 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set3 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set3", "double", 0, "torque_set3", "", &my_cfgConfig::torque_set3)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set3", "double", 0, "torque_set3", "", &my_cfgConfig::torque_set3)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set4 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set4 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set4 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set4", "double", 0, "torque_set4", "", &my_cfgConfig::torque_set4)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set4", "double", 0, "torque_set4", "", &my_cfgConfig::torque_set4)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set5 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set5 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set5 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set5", "double", 0, "torque_set5", "", &my_cfgConfig::torque_set5)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set5", "double", 0, "torque_set5", "", &my_cfgConfig::torque_set5)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set6 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set6 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set6 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set6", "double", 0, "torque_set6", "", &my_cfgConfig::torque_set6)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set6", "double", 0, "torque_set6", "", &my_cfgConfig::torque_set6)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set7 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set7 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set7 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set7", "double", 0, "torque_set7", "", &my_cfgConfig::torque_set7)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set7", "double", 0, "torque_set7", "", &my_cfgConfig::torque_set7)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set8 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set8 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set8 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set8", "double", 0, "torque_set8", "", &my_cfgConfig::torque_set8)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set8", "double", 0, "torque_set8", "", &my_cfgConfig::torque_set8)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.torque_set9 = -4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.torque_set9 = 4.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.torque_set9 = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set9", "double", 0, "torque_set9", "", &my_cfgConfig::torque_set9)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("torque_set9", "double", 0, "torque_set9", "", &my_cfgConfig::torque_set9)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kp_set = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kp_set = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kp_set = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("kp_set", "double", 0, "kp", "", &my_cfgConfig::kp_set)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("kp_set", "double", 0, "kp", "", &my_cfgConfig::kp_set)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kd_set = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kd_set = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kd_set = 0.8;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("kd_set", "double", 0, "kd", "", &my_cfgConfig::kd_set)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(my_cfgConfig::AbstractParamDescriptionConstPtr(new my_cfgConfig::ParamDescription<double>("kd_set", "double", 0, "kd", "", &my_cfgConfig::kd_set)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(my_cfgConfig::AbstractGroupDescriptionConstPtr(new my_cfgConfig::GroupDescription<my_cfgConfig::DEFAULT, my_cfgConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<my_cfgConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<my_cfgConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<my_cfgConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    my_cfgConfig __max__;
    my_cfgConfig __min__;
    my_cfgConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const my_cfgConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static my_cfgConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &my_cfgConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const my_cfgConfig &my_cfgConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const my_cfgConfig &my_cfgConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const my_cfgConfig &my_cfgConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<my_cfgConfig::AbstractParamDescriptionConstPtr> &my_cfgConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<my_cfgConfig::AbstractGroupDescriptionConstPtr> &my_cfgConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const my_cfgConfigStatics *my_cfgConfig::__get_statics__()
  {
    const static my_cfgConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = my_cfgConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MY_CFGRECONFIGURATOR_H__
