// Generated by gencpp from file yesense_imu/YesenseIMUSetting.msg
// DO NOT EDIT!


#ifndef YESENSE_IMU_MESSAGE_YESENSEIMUSETTING_H
#define YESENSE_IMU_MESSAGE_YESENSEIMUSETTING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yesense_imu
{
template <class ContainerAllocator>
struct YesenseIMUSetting_
{
  typedef YesenseIMUSetting_<ContainerAllocator> Type;

  YesenseIMUSetting_()
    : class(0)
    , id(0)
    , length(0)
    , msg()  {
    }
  YesenseIMUSetting_(const ContainerAllocator& _alloc)
    : class(0)
    , id(0)
    , length(0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _class_type;
  _class_type class;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _length_type;
  _length_type length;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> const> ConstPtr;

}; // struct YesenseIMUSetting_

typedef ::yesense_imu::YesenseIMUSetting_<std::allocator<void> > YesenseIMUSetting;

typedef boost::shared_ptr< ::yesense_imu::YesenseIMUSetting > YesenseIMUSettingPtr;
typedef boost::shared_ptr< ::yesense_imu::YesenseIMUSetting const> YesenseIMUSettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator2> & rhs)
{
  return lhs.class == rhs.class &&
    lhs.id == rhs.id &&
    lhs.length == rhs.length &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yesense_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e7a91ef26451a647daf3866c66ac74c";
  }

  static const char* value(const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e7a91ef26451a64ULL;
  static const uint64_t static_value2 = 0x7daf3866c66ac74cULL;
};

template<class ContainerAllocator>
struct DataType< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yesense_imu/YesenseIMUSetting";
  }

  static const char* value(const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#uint8 CLASS_PRODUCTION_INFO   = 0\n"
"#uint8 CLASS_BAUDRATE          = 2\n"
"#uint8 CLASS_OUTPUT_FREEQUENCY = 3\n"
"#uint8 CLASS_OUTPUT_CONTENT    = 4\n"
"#uint8 CLASS_STANDARD_PARAM    = 5\n"
"#uint8 CLASS_MODE              = 77   #0x4D\n"
"#uint8 CLASS_NMEA_OUTPUT       = 78   #0x4E\n"
"\n"
"#uint8 ID_REQUEST              = 0\n"
"#uint8 ID_MEMERY               = 1\n"
"#uint8 ID_FLASH                = 2\n"
"\n"
"uint8 class\n"
"uint8 id\n"
"uint8 length\n"
"uint8[] msg\n"
;
  }

  static const char* value(const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class);
      stream.next(m.id);
      stream.next(m.length);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YesenseIMUSetting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yesense_imu::YesenseIMUSetting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yesense_imu::YesenseIMUSetting_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "class: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "msg: ";
    if (v.msg.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.msg.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.msg[i]);
    }
    if (v.msg.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // YESENSE_IMU_MESSAGE_YESENSEIMUSETTING_H
